# import del file .env, [.properties] serve per dire a springboot di interpretare il file env come "properties"
spring.config.import=optional:file:../infra/.env[.properties]
# il nome del applicazione
spring.application.name=GamesBarSpring  
# il link per la database, la prta viene presa dal docker compose 
spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB}

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
#controllo che le'entitty java sono compatibile con flyway
spring.jpa.hibernate.ddl-auto=validate
#Impedisce di mantenere aperta la sessione del database fino alla fine della risposta HTTP
spring.jpa.open-in-view=false

#attivare Flyway
spring.flyway.enabled=true 
# cerca migrazione di sql
spring.flyway.locations=classpath:db/migration
# porta del backend
server.port=8000